### ISSUE TITLE
老哥，有没有兴趣去wiki上开个sd小人图鉴的页面？

### ISSUE THREAD

**Issue by LostMyMind** [Pelom777/AzurLaneSD#1]
然后赋上自己的网址就好

**Comment by Pelom777** [comment]
有，怎么弄

**Comment by Pelom777** [comment]
有，怎么弄

**Comment by Pelom777** [comment]
@LostMyMind 有，请问如何操作

**Comment by LostMyMind** [comment]
去BWIKI登录B站账号，网址是https://wiki.biligame.com/blhx/ ，在右上角搜索框输入你想要建立的页面的名字，没有完全符合的页面就会有个新建页面的提示，然后新建页面就好
这个网址里有海事局的wiki编辑教程，还有审核群号，审核通过后海事局会把你的页面放到首页https://wiki.biligame.com/blhx/%E8%87%AA%E7%94%B1%E6%8A%95%E7%A8%BF%E5%BE%85%E5%AE%A1%E6%A0%B8%E5%8C%BA
不过biwiki上传js很难，似乎需要和b站那边的人沟通，所以我感觉只能用外联的形式来完成了，biwki编辑可以支持部分html标签，但是script标签我试过了，不能用。
另外如果老哥你想上传到bwiki了最好网站等开服后再更新新的sd小人，因为海事局那边不是官方的，所以禁止讨论解包出来的还没出现过的舰娘的数据，怕官方查水表，但是开服后舰娘能获取的时候就睁只眼闭只眼了，老哥你如果有兴趣可以去审核群问问海事局的审核人员。
群号我找了下，是31141925。

**Comment by LostMyMind** [comment]
> @LostMyMind 有，请问如何操作

去BWIKI登录B站账号，网址是https://wiki.biligame.com/blhx/ ，在右上角搜索框输入你想要建立的页面的名字，没有完全符合的页面就会有个新建页面的提示，然后新建页面就好
这个网址里有海事局的wiki编辑教程，还有审核群号，审核通过后海事局会把你的页面放到首页https://wiki.biligame.com/blhx/%E8%87%AA%E7%94%B1%E6%8A%95%E7%A8%BF%E5%BE%85%E5%AE%A1%E6%A0%B8%E5%8C%BA
不过biwiki上传js很难，似乎需要和b站那边的人沟通，所以我感觉只能用外联的形式来完成了，biwki编辑可以支持部分html标签，但是script标签我试过了，不能用。
另外如果老哥你想上传到bwiki了最好网站等开服后再更新新的sd小人，因为海事局那边不是官方的，所以禁止讨论解包出来的还没出现过的舰娘的数据，怕官方查水表，但是开服后舰娘能获取的时候就睁只眼闭只眼了，老哥你如果有兴趣可以去审核群问问海事局的审核人员。
群号我找了下，是31141925。
